os: linux
dist: bionic
language: java
jdk: openjdk10

env:
  global:
    # Android SDK tools package to use
    - ANDROID_SDK_URL=https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
    - ANDROID_SDK_SHA256=89f308315e041c93a37a79e0627c47f21d5c5edbe5e80ea8dc0aac8a649e0e92

    # Android compile targets
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.0

    # Emulator
    - EMULATOR_FLAVOUR=default

    # These are all constants -- you shouldn't need to update these.
    - ANDROID_SDK_ROOT=$HOME/android-sdk
    - CMDLINE_TOOLS_ROOT=$ANDROID_SDK_ROOT/cmdline-tools
    - ADB=$ANDROID_SDK_ROOT/platform-tools/adb
    - AVDMANAGER=$CMDLINE_TOOLS_ROOT/tools/bin/avdmanager
    - SDKMANAGER=$CMDLINE_TOOLS_ROOT/tools/bin/sdkmanager
    - EMULATOR=$ANDROID_SDK_ROOT/emulator/emulator

    # Pointless in CI.
    - QEMU_AUDIO_DRV=none

    # Limit RAM usage. Travis has a 4GB limit, we tend to flake otherwise.
    # - JVM_OPTS="-Xms2048M -Xmx2048M -XX:MaxMetaspaceSize=1024M -XX:+HeapDumpOnOutOfMemoryError"

jobs:
  include:
    # This only runs "assemble", which compiles the code and runs non-Android unit tests. This is
    # normally fast -- and allows quick feedback in case of compiler errors (before running the
    # more expensive test cases).
    #
    # This is run in parallel (debug + dev + release)
    - stage: assemble and unit test
      env: TARGET=jvm
      script:
        - ./gradlew :jvmcli:installShadowDist jvmCliTest -s
        - ./.travis/jvmcli_test.sh
    - env: TARGET=android
      script: ./gradlew assembleDebug lintDebug testDebugUnitTest --no-parallel --no-scan -s -PLINT_FATAL=1
    - env: TARGET=android
      script: ./gradlew assembleDev lintDev testDevUnitTest --no-parallel --no-scan -s  -PLINT_FATAL=1
    - env: TARGET=android
      script: ./gradlew assembleRelease lintRelease testReleaseUnitTest --no-parallel --no-scan -s -PLINT_FATAL=1
    # This runs a build where third_party/protobuf has been deleted because F-Droid
    # https://github.com/metrodroid/metrodroid/issues/640#issuecomment-574491810
    - env: TARGET=android
      script:
        - rm -rf ./third_party/protobuf
        - ./gradlew assembleRelease lintRelease testReleaseUnitTest -s -PLINT_FATAL=1

    # This runs the full test suite, including using the Android emulator.
    - stage: test
      env: EMULATOR_API=16 EMULATOR_ARCH=armeabi-v7a
    - env: EMULATOR_API=16 EMULATOR_ARCH=x86
    - env: EMULATOR_API=18 EMULATOR_ARCH=armeabi-v7a
    # Disabled due to https://issuetracker.google.com/issues/134845202
    # - env: EMULATOR_API=21
    - env: EMULATOR_API=21 EMULATOR_ARCH=x86
    - env: EMULATOR_API=23 EMULATOR_ARCH=x86
    - env: EMULATOR_API=24 EMULATOR_ARCH=armeabi-v7a
    - env: EMULATOR_API=24 EMULATOR_ARCH=x86
    - env: EMULATOR_API=27 EMULATOR_ARCH=x86
    - env: EMULATOR_API=28 EMULATOR_ARCH=x86

  allow_failures:
    # These flake on Travis
    - env: EMULATOR_API=27 EMULATOR_ARCH=x86
    - env: EMULATOR_API=28 EMULATOR_ARCH=x86

before_install:
  - travis_retry sudo apt-get update
  # qemu-system-armel: libpulse0
  - travis_retry sudo apt-get install -y libpulse0

install:
  - travis_retry ./.travis/install_android_sdk.sh
  - travis_retry ./.travis/install_android_emulator.sh

script:
  - ./gradlew :assembleAndroidTest
  - ./.travis/start_android_emulator.sh || travis_terminate 1
  - ./gradlew :connectedAndroidTest

after_failure:
  - uname -a || true
  - lscpu || true
  - free -m || true
  - ps faux || true

before_cache:
  - ./gradlew --stop

  # Gradle, general files
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/journal-1/
  # Appears non-hermetic
  - rm -f  $HOME/.gradle/caches/transforms-2/files-2.1/*/android.jar

  # Gradle, version-specific files
  - rm -fr $HOME/.gradle/caches/*/executionHistory/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
  - rm -f  $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
